export const DEFAULT_DIFFICULTY = {
  ENCRYPTED: {
    hintEnabled: 1,
    intelNoiseRate: 0.0,
    reportLatencyMult: 0.9,
    exposureMult: 0.8,
    leakChancePerTurn: 0.0,
    leakImpactMult: 0.8,
    misinfoProb: 0.0,
    fakeTaskInjectionRate: 0.0,
    doubleAgentMonthly: 0.0,
    loyaltySystemEnabled: 0,
    failureFlagRate: 0.0,
    instantFailPolicy: "Guard",
    pressSensitivity: 0.85,
    pressDecayMult: 1.05,
    bureaucracyPressureInit: 0.0,
    interagencyVetoBase: 0.05,
    enemyAlertnessBase: 0.1,
    scoreWeightsProfile: "E1",
    chainTransferLossMult: 0.5,
    humintReliability: 0.85,
  },
  DECRYPTED: {
    hintEnabled: 0,
    briefOnDemandPerWeek: 1,
    intelNoiseRate: 0.02,
    reportLatencyMult: 1.0,
    exposureMult: 1.0,
    leakChancePerTurn: 0.01,
    leakImpactMult: 1.0,
    misinfoProb: 0.0,
    fakeTaskInjectionRate: 0.0,
    doubleAgentMonthly: 0.0,
    loyaltySystemEnabled: 0,
    failureFlagRate: 0.02,
    instantFailPolicy: "Review",
    pressSensitivity: 1.0,
    pressDecayMult: 1.0,
    bureaucracyPressureInit: 0.3,
    interagencyVetoBase: 0.12,
    enemyAlertnessBase: 0.15,
    scoreWeightsProfile: "D1",
    chainTransferLossMult: 1.0,
    humintReliability: 0.78,
  },
  EXPOSED: {
    hintEnabled: 0,
    briefOnDemandPerWeek: 0,
    intelNoiseRate: 0.15,
    reportLatencyMult: 1.15,
    exposureMult: 1.25,
    leakChancePerTurn: 0.04,
    leakImpactMult: 1.25,
    misinfoProb: 0.15,
    fakeTaskInjectionRate: 0.05,
    doubleAgentMonthly: 0.1,
    loyaltySystemEnabled: 1,
    loyaltyJitterPerWeek: 0.01,
    loyaltyDecayBase: 0.02,
    failureFlagRate: 0.06,
    instantFailPolicy: "Strict",
    pressSensitivity: 1.3,
    pressDecayMult: 0.9,
    bureaucracyPressureInit: 0.6,
    interagencyVetoBase: 0.2,
    enemyAlertnessBase: 0.25,
    scoreWeightsProfile: "X1",
    chainTransferLossMult: 1.25,
    humintReliability: 0.65,
  },
};

export function resolveDifficultyProfile(difficultyKey = "DECRYPTED", table = DEFAULT_DIFFICULTY) {
  const resolvedKey = Object.hasOwn(table, difficultyKey) ? difficultyKey : "DECRYPTED";
  return {
    difficulty: resolvedKey,
    profile: { ...(table[resolvedKey] ?? table.DECRYPTED) },
  };
}
